### PR TITLE
feat: use GitHub corner over older GitHub ribbon

### LINKED ISSUE #9: consider using GitHub corner over older GitHub ribbon
I think using https://github.com/tholman/github-corners might provide a nicer aesthetic to https://thonny.org/.

https://thonny.org/ currently looks like this.

image

### PR DESCRIPTION
**Pull request by hirehamir**
closes #9.

### CODE REVIEW

**Comment by hirehamir** [comment]
# Without this change

image

# With this change

image

**Comment by aivarannamaa** [comment]
Thanks and sorry for late reply.

Alright, let's try something different.

**Comment by hirehamir** [comment]
You're welcome! No worries; I'm glad I was able to help.

**Comment by hirehamir** [comment]
It looks nice in production!

image

**Comment by hamirmahal** [comment]
(Screen recording)
https://github.com/thonny/thonny-webpage/assets/43425812/8c8a2aab-f3b7-479d-b0c3-56ed386165a5

**Comment by hirehamir** [comment]
Here's a screen recording of it in production.

https://github.com/thonny/thonny-webpage/assets/43425812/49f30e03-133d-4ed5-95e5-4bda739619a5

**Pull request merged**
